configs:
  params:
    server:
      insecure: true

  redis-ha:
    enabled: true
    redis:
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          memory: 64Mi

    sentinel:
      resources:
        requests:
          cpu: 100m
          memory: 16Mi
        limits:
          memory: 16Mi

    splitBrainDetection:
      resources:
        requests:
          cpu: 50m
          memory: 16Mi
        limits:
          memory: 16Mi

    haproxy:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          memory: 128Mi

  controller:
    replicas: 2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    resources:
      requests:
        cpu: 400m
        memory: 1024Mi
      limits:
        memory: 1024Mi

  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        memory: 256Mi

  server:
    autoscaling:
      enabled: true
      minReplicas: 2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 128Mi

  dex:
    enabled: false

  applicationSet:
    replicas: 2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 64Mi

  notifications:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 64Mi