apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: custom-general-purpose
  labels:
    app.kubernetes.io/managed-by: tofu
spec:
  disruption:
    budgets:
      - nodes: 10%
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    spec:
      expireAfter: 336h
      terminationGracePeriod: 24h
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: custom
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: [ "on-demand", "reserved" ]
        - key: eks.amazonaws.com/instance-category
          operator: In
          values: [ "m", "c", "r" ]
        - key: kubernetes.io/arch
          operator: In
          values: [ "arm64" ]
        - key: kubernetes.io/os
          operator: In
          values: [ "linux" ]
        - key: eks.amazonaws.com/instance-generation
          operator: Gt
          values: [ "6" ]
