apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${region}-${environment}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/monkescience/gitops
    targetRevision: HEAD
    path: apps/${region}-${environment}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
