import:
  - catalog/api-gateway
  - catalog/bootstrap
  - catalog/ecr
  - catalog/ecr-pull-though-cache
  - catalog/eks
  - catalog/eks-argocd
  - catalog/eks-setup
  - catalog/github
  - catalog/private-domain
  - catalog/secret
  - catalog/vpc
  - catalog/vpn

vars:
  namespace: monke
  tenant: core
  environment: dev
  stage: dev
  project: monke
  region: eu-central-1

terraform:
  backend_type: s3
  backend:
    s3:
      bucket: monke-eu-central-1-dev-iac-tofu-state
      region: eu-central-1
      encrypt: true
      use_lockfile: true
